/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.osb.scv.user.mapper.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.osb.scv.user.mapper.model.MappingDataSource;
import com.liferay.osb.scv.user.mapper.model.MappingDataSourceModel;
import com.liferay.osb.scv.user.mapper.model.MappingDataSourceSoap;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the MappingDataSource service. Represents a row in the &quot;OSB_SCV_MappingDataSource&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link MappingDataSourceModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link MappingDataSourceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see MappingDataSourceImpl
 * @see MappingDataSource
 * @see MappingDataSourceModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class MappingDataSourceModelImpl extends BaseModelImpl<MappingDataSource>
	implements MappingDataSourceModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a mapping data source model instance should use the {@link MappingDataSource} interface instead.
	 */
	public static final String TABLE_NAME = "OSB_SCV_MappingDataSource";
	public static final Object[][] TABLE_COLUMNS = {
			{ "mappingDataSourceId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "name", Types.VARCHAR },
			{ "url", Types.VARCHAR },
			{ "login", Types.VARCHAR },
			{ "password_", Types.VARCHAR },
			{ "type_", Types.BIGINT },
			{ "availableFields", Types.CLOB }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("mappingDataSourceId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("url", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("login", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("password_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("type_", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("availableFields", Types.CLOB);
	}

	public static final String TABLE_SQL_CREATE = "create table OSB_SCV_MappingDataSource (mappingDataSourceId LONG not null primary key,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,name VARCHAR(75) null,url VARCHAR(75) null,login VARCHAR(75) null,password_ VARCHAR(75) null,type_ LONG,availableFields TEXT null)";
	public static final String TABLE_SQL_DROP = "drop table OSB_SCV_MappingDataSource";
	public static final String ORDER_BY_JPQL = " ORDER BY mappingDataSource.mappingDataSourceId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY OSB_SCV_MappingDataSource.mappingDataSourceId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.osb.scv.user.mapper.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.com.liferay.osb.scv.user.mapper.model.MappingDataSource"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.osb.scv.user.mapper.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.com.liferay.osb.scv.user.mapper.model.MappingDataSource"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.osb.scv.user.mapper.service.util.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.liferay.osb.scv.user.mapper.model.MappingDataSource"),
			true);
	public static final long COMPANYID_COLUMN_BITMASK = 1L;
	public static final long MAPPINGDATASOURCEID_COLUMN_BITMASK = 2L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static MappingDataSource toModel(MappingDataSourceSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		MappingDataSource model = new MappingDataSourceImpl();

		model.setMappingDataSourceId(soapModel.getMappingDataSourceId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setName(soapModel.getName());
		model.setUrl(soapModel.getUrl());
		model.setLogin(soapModel.getLogin());
		model.setPassword(soapModel.getPassword());
		model.setType(soapModel.getType());
		model.setAvailableFields(soapModel.getAvailableFields());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<MappingDataSource> toModels(
		MappingDataSourceSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<MappingDataSource> models = new ArrayList<MappingDataSource>(soapModels.length);

		for (MappingDataSourceSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.osb.scv.user.mapper.service.util.ServiceProps.get(
				"lock.expiration.time.com.liferay.osb.scv.user.mapper.model.MappingDataSource"));

	public MappingDataSourceModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _mappingDataSourceId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setMappingDataSourceId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _mappingDataSourceId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return MappingDataSource.class;
	}

	@Override
	public String getModelClassName() {
		return MappingDataSource.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("mappingDataSourceId", getMappingDataSourceId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("name", getName());
		attributes.put("url", getUrl());
		attributes.put("login", getLogin());
		attributes.put("password", getPassword());
		attributes.put("type", getType());
		attributes.put("availableFields", getAvailableFields());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long mappingDataSourceId = (Long)attributes.get("mappingDataSourceId");

		if (mappingDataSourceId != null) {
			setMappingDataSourceId(mappingDataSourceId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		String name = (String)attributes.get("name");

		if (name != null) {
			setName(name);
		}

		String url = (String)attributes.get("url");

		if (url != null) {
			setUrl(url);
		}

		String login = (String)attributes.get("login");

		if (login != null) {
			setLogin(login);
		}

		String password = (String)attributes.get("password");

		if (password != null) {
			setPassword(password);
		}

		Long type = (Long)attributes.get("type");

		if (type != null) {
			setType(type);
		}

		String availableFields = (String)attributes.get("availableFields");

		if (availableFields != null) {
			setAvailableFields(availableFields);
		}
	}

	@JSON
	@Override
	public long getMappingDataSourceId() {
		return _mappingDataSourceId;
	}

	@Override
	public void setMappingDataSourceId(long mappingDataSourceId) {
		_mappingDataSourceId = mappingDataSourceId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return StringPool.BLANK;
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return StringPool.BLANK;
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_name = name;
	}

	@JSON
	@Override
	public String getUrl() {
		if (_url == null) {
			return StringPool.BLANK;
		}
		else {
			return _url;
		}
	}

	@Override
	public void setUrl(String url) {
		_url = url;
	}

	@JSON
	@Override
	public String getLogin() {
		if (_login == null) {
			return StringPool.BLANK;
		}
		else {
			return _login;
		}
	}

	@Override
	public void setLogin(String login) {
		_login = login;
	}

	@JSON
	@Override
	public String getPassword() {
		if (_password == null) {
			return StringPool.BLANK;
		}
		else {
			return _password;
		}
	}

	@Override
	public void setPassword(String password) {
		_password = password;
	}

	@JSON
	@Override
	public long getType() {
		return _type;
	}

	@Override
	public void setType(long type) {
		_type = type;
	}

	@JSON
	@Override
	public String getAvailableFields() {
		if (_availableFields == null) {
			return StringPool.BLANK;
		}
		else {
			return _availableFields;
		}
	}

	@Override
	public void setAvailableFields(String availableFields) {
		_availableFields = availableFields;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			MappingDataSource.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public MappingDataSource toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (MappingDataSource)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		MappingDataSourceImpl mappingDataSourceImpl = new MappingDataSourceImpl();

		mappingDataSourceImpl.setMappingDataSourceId(getMappingDataSourceId());
		mappingDataSourceImpl.setCompanyId(getCompanyId());
		mappingDataSourceImpl.setUserId(getUserId());
		mappingDataSourceImpl.setUserName(getUserName());
		mappingDataSourceImpl.setCreateDate(getCreateDate());
		mappingDataSourceImpl.setModifiedDate(getModifiedDate());
		mappingDataSourceImpl.setName(getName());
		mappingDataSourceImpl.setUrl(getUrl());
		mappingDataSourceImpl.setLogin(getLogin());
		mappingDataSourceImpl.setPassword(getPassword());
		mappingDataSourceImpl.setType(getType());
		mappingDataSourceImpl.setAvailableFields(getAvailableFields());

		mappingDataSourceImpl.resetOriginalValues();

		return mappingDataSourceImpl;
	}

	@Override
	public int compareTo(MappingDataSource mappingDataSource) {
		long primaryKey = mappingDataSource.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof MappingDataSource)) {
			return false;
		}

		MappingDataSource mappingDataSource = (MappingDataSource)obj;

		long primaryKey = mappingDataSource.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		MappingDataSourceModelImpl mappingDataSourceModelImpl = this;

		mappingDataSourceModelImpl._originalCompanyId = mappingDataSourceModelImpl._companyId;

		mappingDataSourceModelImpl._setOriginalCompanyId = false;

		mappingDataSourceModelImpl._setModifiedDate = false;

		mappingDataSourceModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<MappingDataSource> toCacheModel() {
		MappingDataSourceCacheModel mappingDataSourceCacheModel = new MappingDataSourceCacheModel();

		mappingDataSourceCacheModel.mappingDataSourceId = getMappingDataSourceId();

		mappingDataSourceCacheModel.companyId = getCompanyId();

		mappingDataSourceCacheModel.userId = getUserId();

		mappingDataSourceCacheModel.userName = getUserName();

		String userName = mappingDataSourceCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			mappingDataSourceCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			mappingDataSourceCacheModel.createDate = createDate.getTime();
		}
		else {
			mappingDataSourceCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			mappingDataSourceCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			mappingDataSourceCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		mappingDataSourceCacheModel.name = getName();

		String name = mappingDataSourceCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			mappingDataSourceCacheModel.name = null;
		}

		mappingDataSourceCacheModel.url = getUrl();

		String url = mappingDataSourceCacheModel.url;

		if ((url != null) && (url.length() == 0)) {
			mappingDataSourceCacheModel.url = null;
		}

		mappingDataSourceCacheModel.login = getLogin();

		String login = mappingDataSourceCacheModel.login;

		if ((login != null) && (login.length() == 0)) {
			mappingDataSourceCacheModel.login = null;
		}

		mappingDataSourceCacheModel.password = getPassword();

		String password = mappingDataSourceCacheModel.password;

		if ((password != null) && (password.length() == 0)) {
			mappingDataSourceCacheModel.password = null;
		}

		mappingDataSourceCacheModel.type = getType();

		mappingDataSourceCacheModel.availableFields = getAvailableFields();

		String availableFields = mappingDataSourceCacheModel.availableFields;

		if ((availableFields != null) && (availableFields.length() == 0)) {
			mappingDataSourceCacheModel.availableFields = null;
		}

		return mappingDataSourceCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(25);

		sb.append("{mappingDataSourceId=");
		sb.append(getMappingDataSourceId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", name=");
		sb.append(getName());
		sb.append(", url=");
		sb.append(getUrl());
		sb.append(", login=");
		sb.append(getLogin());
		sb.append(", password=");
		sb.append(getPassword());
		sb.append(", type=");
		sb.append(getType());
		sb.append(", availableFields=");
		sb.append(getAvailableFields());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(40);

		sb.append("<model><model-name>");
		sb.append("com.liferay.osb.scv.user.mapper.model.MappingDataSource");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>mappingDataSourceId</column-name><column-value><![CDATA[");
		sb.append(getMappingDataSourceId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>name</column-name><column-value><![CDATA[");
		sb.append(getName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>url</column-name><column-value><![CDATA[");
		sb.append(getUrl());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>login</column-name><column-value><![CDATA[");
		sb.append(getLogin());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>password</column-name><column-value><![CDATA[");
		sb.append(getPassword());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>type</column-name><column-value><![CDATA[");
		sb.append(getType());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>availableFields</column-name><column-value><![CDATA[");
		sb.append(getAvailableFields());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = MappingDataSource.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			MappingDataSource.class
		};
	private long _mappingDataSourceId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _name;
	private String _url;
	private String _login;
	private String _password;
	private long _type;
	private String _availableFields;
	private long _columnBitmask;
	private MappingDataSource _escapedModel;
}