/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.osb.scv.user.mapper.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.osb.scv.user.mapper.model.MappingDataSource;
import com.liferay.osb.scv.user.mapper.service.MappingDataSourceLocalServiceUtil;

/**
 * The extended model base implementation for the MappingDataSource service. Represents a row in the &quot;OSB_SCV_MappingDataSource&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link MappingDataSourceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see MappingDataSourceImpl
 * @see MappingDataSource
 * @generated
 */
@ProviderType
public abstract class MappingDataSourceBaseImpl
	extends MappingDataSourceModelImpl implements MappingDataSource {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a mapping data source model instance should use the {@link MappingDataSource} interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			MappingDataSourceLocalServiceUtil.addMappingDataSource(this);
		}
		else {
			MappingDataSourceLocalServiceUtil.updateMappingDataSource(this);
		}
	}
}