/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.osb.scv.user.mapper.service.base;

import aQute.bnd.annotation.ProviderType;

import com.liferay.osb.scv.user.mapper.model.MappingDataSource;
import com.liferay.osb.scv.user.mapper.service.MappingDataSourceLocalService;
import com.liferay.osb.scv.user.mapper.service.persistence.MappingDataSourcePersistence;
import com.liferay.osb.scv.user.mapper.service.persistence.UserMappingRulePersistence;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalServiceRegistry;
import com.liferay.portal.kernel.service.persistence.ClassNamePersistence;
import com.liferay.portal.kernel.service.persistence.UserPersistence;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.spring.extender.service.ServiceReference;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the mapping data source local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.osb.scv.user.mapper.service.impl.MappingDataSourceLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.liferay.osb.scv.user.mapper.service.impl.MappingDataSourceLocalServiceImpl
 * @see com.liferay.osb.scv.user.mapper.service.MappingDataSourceLocalServiceUtil
 * @generated
 */
@ProviderType
public abstract class MappingDataSourceLocalServiceBaseImpl
	extends BaseLocalServiceImpl implements MappingDataSourceLocalService,
		IdentifiableOSGiService {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.liferay.osb.scv.user.mapper.service.MappingDataSourceLocalServiceUtil} to access the mapping data source local service.
	 */

	/**
	 * Adds the mapping data source to the database. Also notifies the appropriate model listeners.
	 *
	 * @param mappingDataSource the mapping data source
	 * @return the mapping data source that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public MappingDataSource addMappingDataSource(
		MappingDataSource mappingDataSource) {
		mappingDataSource.setNew(true);

		return mappingDataSourcePersistence.update(mappingDataSource);
	}

	/**
	 * Creates a new mapping data source with the primary key. Does not add the mapping data source to the database.
	 *
	 * @param mappingDataSourceId the primary key for the new mapping data source
	 * @return the new mapping data source
	 */
	@Override
	public MappingDataSource createMappingDataSource(long mappingDataSourceId) {
		return mappingDataSourcePersistence.create(mappingDataSourceId);
	}

	/**
	 * Deletes the mapping data source with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param mappingDataSourceId the primary key of the mapping data source
	 * @return the mapping data source that was removed
	 * @throws PortalException if a mapping data source with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public MappingDataSource deleteMappingDataSource(long mappingDataSourceId)
		throws PortalException {
		return mappingDataSourcePersistence.remove(mappingDataSourceId);
	}

	/**
	 * Deletes the mapping data source from the database. Also notifies the appropriate model listeners.
	 *
	 * @param mappingDataSource the mapping data source
	 * @return the mapping data source that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public MappingDataSource deleteMappingDataSource(
		MappingDataSource mappingDataSource) {
		return mappingDataSourcePersistence.remove(mappingDataSource);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(MappingDataSource.class,
			clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return mappingDataSourcePersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.liferay.osb.scv.user.mapper.model.impl.MappingDataSourceModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery, int start,
		int end) {
		return mappingDataSourcePersistence.findWithDynamicQuery(dynamicQuery,
			start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.liferay.osb.scv.user.mapper.model.impl.MappingDataSourceModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery, int start,
		int end, OrderByComparator<T> orderByComparator) {
		return mappingDataSourcePersistence.findWithDynamicQuery(dynamicQuery,
			start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return mappingDataSourcePersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery,
		Projection projection) {
		return mappingDataSourcePersistence.countWithDynamicQuery(dynamicQuery,
			projection);
	}

	@Override
	public MappingDataSource fetchMappingDataSource(long mappingDataSourceId) {
		return mappingDataSourcePersistence.fetchByPrimaryKey(mappingDataSourceId);
	}

	/**
	 * Returns the mapping data source with the primary key.
	 *
	 * @param mappingDataSourceId the primary key of the mapping data source
	 * @return the mapping data source
	 * @throws PortalException if a mapping data source with the primary key could not be found
	 */
	@Override
	public MappingDataSource getMappingDataSource(long mappingDataSourceId)
		throws PortalException {
		return mappingDataSourcePersistence.findByPrimaryKey(mappingDataSourceId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery = new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(mappingDataSourceLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(MappingDataSource.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("mappingDataSourceId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery getIndexableActionableDynamicQuery() {
		IndexableActionableDynamicQuery indexableActionableDynamicQuery = new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(mappingDataSourceLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(MappingDataSource.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"mappingDataSourceId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {
		actionableDynamicQuery.setBaseLocalService(mappingDataSourceLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(MappingDataSource.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("mappingDataSourceId");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {
		return mappingDataSourceLocalService.deleteMappingDataSource((MappingDataSource)persistedModel);
	}

	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {
		return mappingDataSourcePersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the mapping data sources.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.liferay.osb.scv.user.mapper.model.impl.MappingDataSourceModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param start the lower bound of the range of mapping data sources
	 * @param end the upper bound of the range of mapping data sources (not inclusive)
	 * @return the range of mapping data sources
	 */
	@Override
	public List<MappingDataSource> getMappingDataSources(int start, int end) {
		return mappingDataSourcePersistence.findAll(start, end);
	}

	/**
	 * Returns the number of mapping data sources.
	 *
	 * @return the number of mapping data sources
	 */
	@Override
	public int getMappingDataSourcesCount() {
		return mappingDataSourcePersistence.countAll();
	}

	/**
	 * Updates the mapping data source in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param mappingDataSource the mapping data source
	 * @return the mapping data source that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public MappingDataSource updateMappingDataSource(
		MappingDataSource mappingDataSource) {
		return mappingDataSourcePersistence.update(mappingDataSource);
	}

	/**
	 * Returns the mapping data source local service.
	 *
	 * @return the mapping data source local service
	 */
	public MappingDataSourceLocalService getMappingDataSourceLocalService() {
		return mappingDataSourceLocalService;
	}

	/**
	 * Sets the mapping data source local service.
	 *
	 * @param mappingDataSourceLocalService the mapping data source local service
	 */
	public void setMappingDataSourceLocalService(
		MappingDataSourceLocalService mappingDataSourceLocalService) {
		this.mappingDataSourceLocalService = mappingDataSourceLocalService;
	}

	/**
	 * Returns the mapping data source persistence.
	 *
	 * @return the mapping data source persistence
	 */
	public MappingDataSourcePersistence getMappingDataSourcePersistence() {
		return mappingDataSourcePersistence;
	}

	/**
	 * Sets the mapping data source persistence.
	 *
	 * @param mappingDataSourcePersistence the mapping data source persistence
	 */
	public void setMappingDataSourcePersistence(
		MappingDataSourcePersistence mappingDataSourcePersistence) {
		this.mappingDataSourcePersistence = mappingDataSourcePersistence;
	}

	/**
	 * Returns the user mapping rule local service.
	 *
	 * @return the user mapping rule local service
	 */
	public com.liferay.osb.scv.user.mapper.service.UserMappingRuleLocalService getUserMappingRuleLocalService() {
		return userMappingRuleLocalService;
	}

	/**
	 * Sets the user mapping rule local service.
	 *
	 * @param userMappingRuleLocalService the user mapping rule local service
	 */
	public void setUserMappingRuleLocalService(
		com.liferay.osb.scv.user.mapper.service.UserMappingRuleLocalService userMappingRuleLocalService) {
		this.userMappingRuleLocalService = userMappingRuleLocalService;
	}

	/**
	 * Returns the user mapping rule persistence.
	 *
	 * @return the user mapping rule persistence
	 */
	public UserMappingRulePersistence getUserMappingRulePersistence() {
		return userMappingRulePersistence;
	}

	/**
	 * Sets the user mapping rule persistence.
	 *
	 * @param userMappingRulePersistence the user mapping rule persistence
	 */
	public void setUserMappingRulePersistence(
		UserMappingRulePersistence userMappingRulePersistence) {
		this.userMappingRulePersistence = userMappingRulePersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the class name local service.
	 *
	 * @return the class name local service
	 */
	public com.liferay.portal.kernel.service.ClassNameLocalService getClassNameLocalService() {
		return classNameLocalService;
	}

	/**
	 * Sets the class name local service.
	 *
	 * @param classNameLocalService the class name local service
	 */
	public void setClassNameLocalService(
		com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService) {
		this.classNameLocalService = classNameLocalService;
	}

	/**
	 * Returns the class name persistence.
	 *
	 * @return the class name persistence
	 */
	public ClassNamePersistence getClassNamePersistence() {
		return classNamePersistence;
	}

	/**
	 * Sets the class name persistence.
	 *
	 * @param classNamePersistence the class name persistence
	 */
	public void setClassNamePersistence(
		ClassNamePersistence classNamePersistence) {
		this.classNamePersistence = classNamePersistence;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.kernel.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.kernel.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.kernel.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		persistedModelLocalServiceRegistry.register("com.liferay.osb.scv.user.mapper.model.MappingDataSource",
			mappingDataSourceLocalService);
	}

	public void destroy() {
		persistedModelLocalServiceRegistry.unregister(
			"com.liferay.osb.scv.user.mapper.model.MappingDataSource");
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return MappingDataSourceLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return MappingDataSource.class;
	}

	protected String getModelClassName() {
		return MappingDataSource.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = mappingDataSourcePersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = MappingDataSourceLocalService.class)
	protected MappingDataSourceLocalService mappingDataSourceLocalService;
	@BeanReference(type = MappingDataSourcePersistence.class)
	protected MappingDataSourcePersistence mappingDataSourcePersistence;
	@BeanReference(type = com.liferay.osb.scv.user.mapper.service.UserMappingRuleLocalService.class)
	protected com.liferay.osb.scv.user.mapper.service.UserMappingRuleLocalService userMappingRuleLocalService;
	@BeanReference(type = UserMappingRulePersistence.class)
	protected UserMappingRulePersistence userMappingRulePersistence;
	@ServiceReference(type = com.liferay.counter.kernel.service.CounterLocalService.class)
	protected com.liferay.counter.kernel.service.CounterLocalService counterLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.ClassNameLocalService.class)
	protected com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService;
	@ServiceReference(type = ClassNamePersistence.class)
	protected ClassNamePersistence classNamePersistence;
	@ServiceReference(type = com.liferay.portal.kernel.service.ResourceLocalService.class)
	protected com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.UserLocalService.class)
	protected com.liferay.portal.kernel.service.UserLocalService userLocalService;
	@ServiceReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	@ServiceReference(type = PersistedModelLocalServiceRegistry.class)
	protected PersistedModelLocalServiceRegistry persistedModelLocalServiceRegistry;
}